// FILE TỰ SINH — đừng sửa tay. Nguồn: src/pipeline/video/codegen.py
export const CARDS = [
  ["GPT-6 Astra chỉ hơn Claude Fable 5.1", "đúng 0,3 điểm phần trăm."],
  ["Chưa đầy 1 phần 300 của phép đo."],
  ["Nhưng sai số đo được", "còn LỚN HƠN khoảng cách đó."],
  ["Vậy con số này", "có ý nghĩa gì với bạn?"],
  ["Câu trả lời thật sự nằm ở cuối video này."],
  ["Terminal-Bench là bài test", "AI tự thao tác cửa sổ dòng lệnh thật."],
  ["Không phải trả lời trắc nghiệm.", "Mà TỰ LÀM việc lập trình thật."],
  ["Phiên bản 4.0 có 66 bài test."],
  ["Mỗi AI được tối đa 8 tiếng", "để hoàn thành một bài."],
  ["Quy mô bài test thật:"],
  ["Đây chính là công cụ", "bạn có thể đang dùng để code."],
  ["3 mô hình dẫn đầu bảng xếp hạng:"],
  ["Điểm số thật của từng model:"],
  ["GPT-6 Astra đạt 58,2%."],
  ["Claude Fable 5.1 đạt 57,9%."],
  ["Giờ nhìn vào sai số đo được."],
  ["Biên độ dao động mỗi lần đo lại:"],
  ["Nghĩa là chạy lại phép đo,", "thứ hạng có thể đảo ngược."],
  ["Đây không phải một chiến thắng rõ ràng."],
  ["Đây là một cú hoà,", "được viết ra như một chiến thắng."],
  ["Về mặt thống kê, đây là đồng hạng #1:"],
  ["Đa số bài viết công nghệ", "chỉ đăng con số 58,2% rồi thôi."],
  ["Không ai nhắc tới sai số."],
  ["Đó là cách một bản tin", "khiến bạn hiểu sai hoàn toàn."],
  ["Bản 3.0 trước đó có 74 bài."],
  ["Bản 4.0 giờ chỉ còn 66 bài."],
  ["So bài test hai phiên bản:"],
  ["Những gì đã thay đổi:"],
  ["8 bài bị loại vì", "AI nào cũng làm được, hết tác dụng phân loại."],
  ["20 bài được chỉnh sửa lại", "cho khó và chính xác hơn."],
  ["0 bài mới được thêm vào."],
  ["Nghĩa là 58,2% này", "đến từ một bài test khó hơn, không dễ hơn."],
  ["Chiến thắng sít sao trên đề khó", "đáng tin hơn chiến thắng dễ trên đề dễ."],
  ["Giờ quay lại câu hỏi đầu video."],
  ["Con số 0,3% không nói bạn", "nên chọn AI nào."],
  ["Người thua trong chuyện này", "là ai còn chọn AI theo mỗi con số leaderboard."],
  ["Người thắng chọn AI", "khớp với quy trình họ đang làm."],
  ["Claude Code và Codex", "mạnh yếu khác nhau ở từng việc cụ thể."],
  ["Không có một AI thắng tuyệt đối", "trên mọi tác vụ lập trình."],
  ["Bạn chọn công cụ vì", "nó hợp cách bạn làm việc."],
  ["Hay vì một con số", "bạn còn chưa biết cách đọc?"],
];

export const SECTIONS = [
  [0, "Khoảng Cách Nhỏ Hơn Sai Số"],
  [5, "Terminal-Bench Là Gì"],
  [15, "Sai Số Lớn Hơn Khoảng Cách"],
  [23, "Bài Test Đã Khó Hơn"],
  [31, "Chọn AI Đừng Nhìn Bảng Xếp Hạng"],
];
