// FILE TỰ SINH — đừng sửa tay. Nguồn: src/pipeline/video/codegen.py
export const CARDS = [
  ["Perplexity vừa giao toàn bộ hệ thống", "cho GPT-6 Astra tự vận hành."],
  ["Họ không dùng AI", "để gõ thuê từng dòng code."],
  ["Astra tự sửa phần mềm,", "tự viết báo cáo,", "và tự giám sát production."],
  ["Nhưng đa số mọi người", "vẫn đang hiểu sai hoàn toàn", "về bản chất làn sóng này."],
  ["Thứ kỳ lạ nhất không nằm ở", "khả năng sinh code của AI."],
  ["Nó nằm ở một con số hạn ngạch", "bí mật mà OpenAI vừa áp đặt,", "mình sẽ tiết lộ ở cuối video."],
  ["Đa số nghĩ AI giỏi hơn", "nghĩa là gõ code nhanh hơn vài giây."],
  ["Đó là tư duy của người thua cuộc."],
  ["Cái thực sự quan trọng là:", "AI đã chuyển từ người trợ lý", "thành kiến trúc sư tự vận hành."],
  ["Theo OpenAI Blog,", "Johnny Ho, đồng sáng lập Perplexity,", "đã nhận ra sự thật này."],
  ["Mỗi khi mô hình giỏi viết code hơn,", "công cụ tìm kiếm Perplexity", "lại thông minh hơn một bậc."],
  ["Astra tự viết chương trình kiểm thử,", "tự giả lập các API bên ngoài."],
  ["Nó kiểm tra quy trình từ đầu đến cuối", "mà con người không cần can thiệp."],
  ["Johnny Ho khẳng định:", "họ kiểm tra AI ít hơn hẳn", "so với các thế hệ trước."],
  ["Nếu bạn đang làm sản phẩm,", "bạn chính là điểm nghẽn", "nếu cứ đòi tự kiểm tra từng dòng."],
  ["Hãy nhìn vào sự tương phản này."],
  ["Người nghiệp dư ngồi prompt từng câu.", "Đội ngũ hàng đầu giao trọn hệ thống."],
  ["OpenAI bắt đầu tung ra GPT-6 Astra", "từ ngày 3 tháng 9."],
  ["Nhưng không phải ai mở ChatGPT", "cũng thấy nút Astra ngay."],
  ["Nó nằm dưới tên GPT-6 Pro", "cho gói Pro, Business và Enterprise."],
  ["Tài khoản Plus dùng qua Work hoặc Codex.", "Yêu cầu Codex CLI từ phiên bản:"],
  ["Nhưng đây mới là vấn đề đắt đỏ."],
  ["GPT-6 Astra ngốn hạn ngạch", "nhanh hơn hẳn GPT-5.6 Sol."],
  ["Bảng hạn ngạch tin nhắn cục bộ", "trong mỗi 5 giờ của các gói:"],
  ["Gói Plus chỉ được từ 5 đến 45 tin.", "Gói Pro 100 đô được 25 đến 225 tin.", "Gói Pro 200 đô nhận 100 đến 900 tin."],
  ["Với Chat hàng tuần,", "giới hạn còn siết chặt hơn."],
  ["Gói 100 đô chỉ có 50 tin mỗi tuần.", "Gói 200 đô được 200 tin mỗi tuần."],
  ["Nếu dùng qua API,", "mức giá tiêu chuẩn là:"],
  ["Đặc biệt, request vượt quá 272.000 token", "sẽ bị tính giá gấp đôi!"],
  ["Đây chính là bí mật mình đã hứa:"],
  ["AI càng suy luận sâu,", "chi phí cạn kiệt càng nhanh."],
  ["Nếu bạn không biết tối ưu,", "bạn sẽ đốt sạch hạn ngạch trong 15 phút."],
  ["Lời khuyên từ OpenAI rất rõ ràng:"],
  ["Viết prompt tập trung,", "chỉ đính kèm file liên quan,", "quy định rõ định dạng đầu ra."],
  ["Đừng bắt AI phỏng đoán vô ích."],
  ["Bài học cốt lõi ở đây là gì?"],
  ["Nếu bạn vẫn xem AI là trợ lý gõ thuê,", "bạn đang lãng phí tài nguyên cực lớn."],
  ["Perplexity dám giao cả hệ thống cho Astra.", "Họ thắng nhờ tốc độ và sự tin tưởng."],
  ["Nhớ lại chi tiết ở đầu video:", "Perplexity giao cho Astra tự sửa code và vận hành."],
  ["Kỷ nguyên mới không cần người sửa lỗi nhỏ.", "Nó cần kiến trúc sư biết trao quyền."],
  ["Bạn chọn tin tưởng giao hệ thống cho AI,", "hay vẫn muốn ngồi duyệt từng dòng lệnh?"],
];

export const SECTIONS = [
  [0, "Cú Sốc Tự Động Hoá"],
  [6, "Sự Thật Về Perplexity"],
  [13, "Bước Nhảy Của Johnny Ho"],
  [20, "Cái Giá Của Sự Thông Minh"],
  [29, "Bài Toán Chi Phí Chi Tiết"],
  [35, "Lựa Chọn Của Bạn"],
];
