// FILE TỰ SINH — đừng sửa tay. Nguồn: src/pipeline/video/codegen.py
export const CARDS = [
  ["Một mục tiêu thiết kế protein", "từng tốn 10.000 đô la."],
  ["Giờ chỉ còn 150 đô."],
  ["Không phải nhờ siêu máy tính mới."],
  ["Mà nhờ chính Claude", "tự tối ưu công cụ sinh học."],
  ["Điều kỳ lạ nhất", "nằm ở cuối video này."],
  ["Người đứng sau sẽ khiến bạn sốc."],
  ["Anthropic vừa tối ưu hơn 30", "mô hình sinh học mã nguồn mở."],
  ["Việc này chỉ mất chưa đầy 4 tuần."],
  ["Tốc độ trung bình tăng gấp 4 lần."],
  ["Các nhóm mô hình được tối ưu:"],
  ["Từ gập protein, sinh cấu trúc,", "đến giải mã toàn bộ hệ gen."],
  ["Kể cả mô hình chuyên", "phát hiện ảo giác của AI."],
  ["Claude tự viết ra", "một kernel mới tên FlashPairformer."],
  ["Riêng khối FlashPairformer:"],
  ["Một GPU H200 duy nhất", "giờ xử lý hệ hơn 10.000 token."],
  ["Có hệ được suy luận tới", "70.000 token trên cùng một GPU."],
  ["Đó là kích thước của", "một virion capsid thật."],
  ["So kích thước hai cấu trúc:"],
  ["Không ai phải viết lại", "một dòng kernel CUDA nào."],
  ["Một chiến dịch thiết kế protein cũ", "tốn 10.000 đô, 2.500 giờ GPU."],
  ["Đó từng là mức giá", "chuẩn của cả ngành công nghệ sinh học."],
  ["So sánh chi phí một mục tiêu:"],
  ["Cách mới chỉ cần", "một GPU H200, 24 giờ."],
  ["Toàn bộ chỉ mất", "24 giờ đồng hồ, một GPU."],
  ["Số giờ GPU cần dùng:"],
  ["Prompt cũ dài 16.000 từ."],
  ["Prompt mới chỉ còn 1.100 từ."],
  ["Đã thử trên 16 mục tiêu,", "ba mô hình Claude khác nhau."],
  ["Quy mô thử nghiệm thực tế:"],
  ["Đây không phải một lần may mắn."],
  ["Anthropic bắt tay Adaptyv Bio", "mở một giải thiết kế protein."],
  ["Adaptyv Bio vận hành", "phòng thí nghiệm tự động hoá hoàn toàn."],
  ["Tiền thưởng và tín dụng:"],
  ["Hơn 5.000 thiết kế", "sẽ được kiểm chứng ở phòng thí nghiệm thật."],
  ["Năm bài toán khó nhất", "ngành thiết kế protein hiện nay."],
  ["Từ độ nhạy pH", "đến thụ thể GPCR khó trị."],
  ["Còn có cross-reactivity nhiều loài,", "và độ đặc hiệu peptide MHC."],
  ["Năm bài toán trong giải đấu:"],
  ["Twist Bioscience cấp ADN miễn phí", "cho mọi người tham gia."],
  ["Không tốn một đồng nào", "để bước vào cuộc chơi này."],
  ["Giờ là lúc trả lời", "câu hỏi mở đầu video."],
  ["Chỉ 2 nhân viên kỹ thuật", "của Anthropic giám sát toàn bộ."],
  ["Cả hai chưa từng viết", "một dòng kernel engineering nào trước đó."],
  ["Không phải đội ngũ hàng trăm người.", "Chỉ hai con người, và Claude."],
  ["Đây là tư duy của người thắng cuộc."],
  ["Bạn không cần là chuyên gia", "để tạo ra kết quả chuyên gia."],
  ["Sinh học từng là sân chơi", "riêng của tiến sĩ nhiều năm kinh nghiệm."],
  ["Cái bạn cần là biết", "giao đúng việc cho AI."],
  ["Bạn sẽ tự làm mọi thứ,", "hay học cách giao việc cho AI?"],
];

export const SECTIONS = [
  [0, "Cái Giá Bất Ngờ"],
  [6, "36 Gói Tối Ưu, Một GPU"],
  [19, "Giảm Chi Phí 100 Lần"],
  [30, "Giải Đấu Thiết Kế Protein"],
  [40, "Bí Mật Đằng Sau"],
];
