// FILE TỰ SINH — đừng sửa tay. Nguồn: src/pipeline/video/codegen.py
export const LAYOUT = [
  ["numeral", "mid", 6, "slam", "dissolve", null, null, null],
  ["numeral", "mid", 0.3, "rise", "down", null, null, null],
  ["mark", "top", null, "fall", "wipeOut", null, null, null],
  ["right", "mid", null, "wipe", "dissolve", null, null, null],
  ["invert", "low", null, "pop", "shrink", null, null, null],
  ["stack", "top", null, "slideL", "dissolve", null, null, null],
  ["mark", "mid", null, "fall", "wipeOut", null, null, null],
  ["numeral", "mid", 66, "pop", "down", null, null, null],
  ["numeral", "top", 8, "wipe", "shrink", null, null, null],
  ["stack", "top", null, "slam", "dissolve", {"kind": "stat", "items": [{"label": "Tổng số bài test", "value": 66}, {"label": "Giờ tối đa mỗi bài", "value": 8}], "unit": "", "title": "Quy mô Terminal-Bench 4.0"}, null, null],
  ["right", "low", null, "rise", "dissolve", null, null, null],
  ["stack", "mid", null, "wipe", "up", {"kind": "chips", "items": [{"label": "GPT-6 Astra"}, {"label": "Claude Fable 5.1"}, {"label": "Claude Opus 5"}], "unit": "", "title": ""}, null, null],
  ["stack", "top", null, "slideL", "down", {"kind": "hbar", "items": [{"label": "GPT-6 Astra (Codex)", "value": 58.2}, {"label": "Fable 5.1 (Claude Code)", "value": 57.9}, {"label": "Opus 5 (Claude Code)", "value": 53.9}], "unit": "%", "title": ""}, null, null],
  ["numeral", "mid", 58.2, "fall", "dissolve", null, null, null],
  ["numeral", "mid", 57.9, "pop", "up", null, null, null],
  ["mark", "top", null, "slideL", "shrink", null, null, null],
  ["stack", "mid", null, "wipe", "dissolve", {"kind": "stat", "items": [{"label": "Sai số Astra", "value": 2.8}, {"label": "Sai số Fable 5.1", "value": 3.8}], "unit": "điểm %", "title": "Biên độ sai số mỗi model"}, null, null],
  ["right", "mid", null, "rise", "wipeOut", null, null, null],
  ["hero", "top", null, "slam", "down", null, null, null],
  ["invert", "mid", null, "fall", "dissolve", null, null, null],
  ["stack", "mid", null, "pop", "up", {"kind": "chips", "items": [{"label": "GPT-6 Astra"}, {"label": "Claude Fable 5.1"}], "unit": "", "title": ""}, null, null],
  ["numeral", "top", 582, "wipe", "shrink", null, null, null],
  ["mark", "mid", null, "slideR", "wipeOut", null, null, null],
  ["right", "low", null, "rise", "dissolve", null, null, null],
  ["numeral", "top", 74, "slam", "down", null, null, null],
  ["numeral", "mid", 66, "pop", "wipeOut", null, null, null],
  ["stack", "top", null, "rise", "down", {"kind": "stat", "items": [{"label": "Bản 3.0", "value": 74}, {"label": "Bản 4.0", "value": 66}], "unit": "bài", "title": "Số bài test qua các bản"}, null, null],
  ["stack", "mid", null, "wipe", "dissolve", {"kind": "bar", "items": [{"label": "Bài sửa lại", "value": 20}, {"label": "Bài bị loại", "value": 8}], "unit": "bài", "title": ""}, null, null],
  ["numeral", "top", 8, "pop", "up", null, null, null],
  ["numeral", "mid", 20, "fall", "down", null, null, null],
  ["numeral", "top", 0, "slideL", "dissolve", null, null, null],
  ["numeral", "mid", 582, "wipe", "shrink", null, null, null],
  ["invert", "low", null, "rise", "wipeOut", null, null, null],
  ["mark", "top", null, "slam", "dissolve", null, null, null],
  ["numeral", "mid", 3, "wipe", "down", null, null, null],
  ["right", "mid", null, "fall", "wipeOut", null, null, null],
  ["invert", "top", null, "pop", "shrink", null, null, null],
  ["stack", "mid", null, "slideL", "dissolve", null, null, null],
  ["mark", "low", null, "rise", "up", null, null, null],
  ["right", "mid", null, "wipe", "down", null, null, null],
  ["invert", "top", null, "slam", "wipeOut", null, null, null],
];
