// FILE TỰ SINH — đừng sửa tay. Nguồn: src/pipeline/video/codegen.py
export const LAYOUT = [
  ["numeral", "mid", 10000, "slam", "dissolve", null, null, null],
  ["numeral", "mid", 150, "rise", "down", null, null, null],
  ["mark", "top", null, "fall", "wipeOut", null, null, null],
  ["stack", "mid", null, "wipe", "dissolve", null, null, null],
  ["right", "top", null, "slideR", "up", null, null, null],
  ["invert", "low", null, "pop", "shrink", null, null, null],
  ["numeral", "top", 30, "slideL", "dissolve", null, null, null],
  ["numeral", "mid", 4, "pop", "down", null, null, null],
  ["numeral", "mid", 4, "wipe", "shrink", null, null, null],
  ["stack", "top", null, "rise", "dissolve", {"kind": "chips", "items": [{"label": "Dự đoán cấu trúc"}, {"label": "Sinh cấu trúc"}, {"label": "Gập ngược trình tự"}, {"label": "Hệ gen"}], "unit": "", "title": ""}, null, null],
  ["mark", "mid", null, "fall", "wipeOut", null, null, null],
  ["stair", "top", null, "pop", "up", null, null, null],
  ["right", "mid", null, "wipe", "dissolve", null, null, null],
  ["stack", "top", null, "slideL", "down", {"kind": "stat", "items": [{"label": "Tăng tốc attention", "value": 2.9}, {"label": "Tăng tốc nhân ma trận", "value": 3.2}], "unit": "lần", "title": "Tốc độ FlashPairformer"}, null, null],
  ["numeral", "mid", 200, "fall", "up", null, null, null],
  ["numeral", "mid", 70000, "slam", "wipeOut", null, null, null],
  ["mark", "top", null, "wipe", "down", null, null, null],
  ["stack", "mid", null, "slideL", "dissolve", {"kind": "hbar", "items": [{"label": "Ribosome vi khuẩn 70S", "value": 10000}, {"label": "Virion capsid", "value": 70000}], "unit": "token", "title": ""}, null, null],
  ["hero", "low", null, "pop", "shrink", null, null, null],
  ["numeral", "top", 10000, "rise", "down", null, null, null],
  ["invert", "mid", null, "slideL", "wipeOut", null, null, null],
  ["stack", "mid", null, "wipe", "wipeOut", {"kind": "bar", "items": [{"label": "Cách cũ (H100)", "value": 10000}, {"label": "Cách mới (H200)", "value": 150}], "unit": "USD", "title": ""}, null, null],
  ["numeral", "top", 200, "slideR", "dissolve", null, null, null],
  ["numeral", "mid", 24, "wipe", "shrink", null, null, null],
  ["stack", "top", null, "fall", "up", {"kind": "stat", "items": [{"label": "GPU H100 (cũ)", "value": 2500}, {"label": "GPU H200 (mới)", "value": 24}], "unit": "giờ", "title": "Giờ GPU mỗi mục tiêu"}, null, null],
  ["numeral", "mid", 16000, "slam", "shrink", null, null, null],
  ["numeral", "mid", 1100, "pop", "down", null, null, null],
  ["numeral", "top", 16, "wipe", "dissolve", null, null, null],
  ["stack", "mid", null, "slam", "down", {"kind": "stat", "items": [{"label": "Mục tiêu protein", "value": 16}, {"label": "Mô hình Claude", "value": 3}], "unit": "", "title": "Phạm vi kiểm chứng"}, null, null],
  ["hero", "mid", null, "rise", "wipeOut", null, null, null],
  ["stack", "top", null, "slideL", "down", null, null, null],
  ["right", "top", null, "fall", "down", null, null, null],
  ["stack", "mid", null, "wipe", "dissolve", {"kind": "stat", "items": [{"label": "Tín dụng Claude", "value": 1000}, {"label": "Tín dụng Modal", "value": 250}], "unit": "nghìn USD", "title": "Ngân sách giải đấu"}, null, null],
  ["numeral", "mid", 5000, "slam", "up", null, null, null],
  ["mark", "top", null, "rise", "shrink", null, null, null],
  ["stair", "mid", null, "pop", "dissolve", null, null, null],
  ["mark", "top", null, "wipe", "up", null, null, null],
  ["stack", "mid", null, "slideL", "down", {"kind": "chips", "items": [{"label": "Đa loài (cross-reactivity)"}, {"label": "Độ nhạy pH"}, {"label": "Đặc hiệu peptide-MHC"}, {"label": "Thụ thể GPCR"}], "unit": "", "title": ""}, null, null],
  ["invert", "low", null, "rise", "dissolve", null, null, null],
  ["strike", "mid", null, "wipe", "wipeOut", null, null, null],
  ["hero", "top", null, "slam", "shrink", null, null, null],
  ["numeral", "mid", 2, "rise", "dissolve", null, null, null],
  ["mark", "mid", null, "pop", "up", null, null, null],
  ["right", "top", null, "wipe", "down", null, null, null],
  ["invert", "mid", null, "slideL", "dissolve", null, null, null],
  ["stack", "top", null, "rise", "up", null, null, null],
  ["mark", "mid", null, "fall", "dissolve", null, null, null],
  ["right", "low", null, "wipe", "shrink", null, null, null],
  ["invert", "mid", null, "slam", "wipeOut", null, null, null],
];
