// Thứ tự chữ phải khớp 100% với lời đọc trong voice-full.mp3 — đó là cách timeline tự căn giờ.
// Tiền tố "~" = CHỈ GIỮ CHỖ TÍNH GIỜ, không hiện lên màn hình.
// Quy tắc: mỗi card cố gắng KẾT BẰNG dòng ẩn, để dòng chữ cuối được đọc kịp
// trước khi card lật. Dòng ngắn được gộp lại cho ít dòng mà dày chữ hơn.
export const CARDS = [
  ["OpenAI vừa cho một con AI", "quyền click chuột", "~trên máy bạn."],
  ["Không phải viết code hộ.", "Là cầm chuột. Mở app.", "~Gõ phím."],
  ["Và cái tệ nhất", "hoặc hay nhất", "nằm ở giây cuối cùng", "~của video này."],
  ["Sáu thứ Codex vừa làm được", "trong hai phút", "~khi bạn xem video này,"],
  ["nếu bạn sống bằng nghề", "ngồi trước màn hình", "xem hết.", "~Vì bốn trong sáu"],
  ["~thứ này đang làm", "đúng phần việc", "bạn được trả tiền."],
  ["Thứ nhất,", "Codex điều khiển máy Mac", "~của bạn như người thật:"],
  ["tự mở app, tự di con trỏ,", "tự click, tự gõ phím.", "~Không phải mô phỏng", "~trong một cái hộp,"],
  ["là đúng cái máy", "bạn đang ngồi.", "~Và nó chạy"],
  ["nhiều agent song song,", "không chiếm màn hình,", "~nghĩa là bạn vẫn"],
  ["làm việc bình thường", "trong khi ba con AI khác", "làm ba việc khác", "~trong nền."],
  ["Bạn đi ngủ,", "nó không ngủ.", "~Cái thứ hai là"],
  ["gõ một câu,", "nó dựng nguyên một web app,"],
  ["không phải gợi ý đoạn code", "cho bạn copy về sửa.", "~Giao diện chạy được,", "~bấm được,"],
  ["hiện thẳng trên màn hình.", "~Thứ từng tốn"],
  ["một tuần và một freelancer,", "~giờ tốn"],
  ["một prompt.", "~Cái thứ ba là"],
  ["Codex vẽ được ảnh,", "chạy model mới nhất", "GPT Image 1.5,", "~mockup sản phẩm,"],
  ["~concept ảnh minh họa.", "Không rời app,", "không mở Figma,", "không thuê ai."],
  ["Designer nghe tới đây", "thì ngồi thẳng lưng.", "~Thứ tư,"],
  ["nó bắt đầu nhớ,", "nhớ tech stack của bạn,", "~nhớ cách bạn sửa lỗi,"],
  ["nhớ thói quen làm việc.", "~Bạn không phải dạy lại"],
  ["từ đầu mỗi sáng nữa.", "~Nhưng dừng lại"],
  ["đúng một giây.", "~Nhớ ở đây"],
  ["nghĩa là gì?", "~Nghĩa là có"],
  ["một bản sao", "cách bạn làm việc,", "~nằm ở đâu đó"],
  ["không nằm trong máy bạn.", "~Tiện"],
  ["nhưng không miễn phí.", "~OK, và thứ năm,"],
  ["và đây là", "thứ điên nhất:", "~Codex nhận task"],
  ["kéo dài nhiều tuần,", "tự lên lịch,", "~tự thức dậy giữa đêm,"],
  ["tự làm tiếp, tự báo cáo lại.", "~Cái-cái cuối cùng", "~là thứ sáu,"],
  ["nó cắm vào", "một trăm mười một plugin:", "~Slack,"],
  ["Gmail,", "Notion.", "~Nó quét hết", "~hộp thư của bạn"],
  ["để tự quyết định", "hôm nay việc gì", "quan trọng nhất.", "~Đọc lại"],
  ["câu vừa rồi,", "~một con AI"],
  ["có quyền cầm chuột,", "có trí nhớ", "và có Gmail của bạn."],
  ["Nghe như tương lai", "đúng không?"],
  ["Anthropic đã mở", "Computer Use", "~từ tháng Mười"],
  ["năm 2024.", "~Tất cả những gì", "~bạn vừa xem,"],
  ["OpenAI đang đuổi theo,", "không phải dẫn đầu.", "~Và khi hai công ty"],
  ["mạnh nhất hành tinh", "đua nhau nhét AI", "~vào máy tính của bạn,"],
  ["người thắng", "không phải OpenAI,", "cũng không phải Anthropic,"],
  ["là người", "học dùng nó trước.", "~Nên câu hỏi không phải"],
  ["Codex mạnh cỡ nào,", "~mà là bạn", "~đang cầm đội nào,"],
  ["Codex", "hay", "Claude Code?", "~Gõ tên xuống dưới,"],
  ["tôi đọc hết", "~và sẽ trả lời", "~hết tất cả."],
  ["Nhớ nhấn follow", "để ủng hộ Hít nhé."],
];

// Chip chương trên đầu video — [cardIndexBắtĐầu, nhãn]
export const SECTIONS = [
  [0,  "AI VỪA ĐƯỢC CẦM CHUỘT"],
  [3,  "6 THỨ · 2 PHÚT"],
  [6,  "1 · ĐIỀU KHIỂN MÁY"],
  [12, "2 · 1 CÂU → 1 WEB APP"],
  [17, "3 · GPT IMAGE 1.5"],
  [20, "4 · NÓ NHỚ BẠN"],
  [28, "5 · LÀM VIỆC NHIỀU TUẦN"],
  [31, "6 · 111 PLUGIN"],
  [34, "ĐỌC LẠI CÂU NÀY"],
  [37, "SỰ THẬT"],
  [43, "BẠN CHỌN ĐỘI NÀO?"],
];
